---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: api
  namespace: {{ .Values.control_plane.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
      - {{ .Values.control_plane.ingressgateway.host }}
    port:
      name: grpc-https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/api-cert/certs/tls.crt
      privateKey: /etc/api-cert/certs/tls.key
...
