---
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  namespace: {{ .Values.app.namespace }}
spec:
  controlPlaneRef:
    name: basic-install
    namespace: {{ .Values.control_plane.namespace }}
...