---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  gateways:
    - {{ .Values.control_plane.namespace }}/api
  hosts:
    - {{ .Values.control_plane.ingressgateway.host }}
  http:
  # Routes for json paths
    - match:
      - uri:
          prefix: /v1/greeter
      route:
      - destination:
          host: {{ .Values.app.name }}
          port:
            number: 50051    
    - match:
      - uri:
          prefix: /{{ .Values.app.grpc.service.name }}
      route:
      - destination:
          host: {{ .Values.app.name }}
          subset: v1
          port:
            number: 50051
    - match:
      - uri:
          prefix: /grpc.reflection.v1alpha.ServerReflection
        headers:
          service:
            exact: {{ .Values.app.grpc.service.name }}
      route:
      - destination:
          host: {{ .Values.app.name }}
          subset: v1
          port:
            number: 50051
...
