apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: api-cert
spec:
  # Secret names are always required.
  secretName: api-cert
  commonName: {{ .Values.control_plane.ingressgateway.host }}
  usages:
    - server auth
    - client auth  
  dnsNames:
    - {{ .Values.control_plane.ingressgateway.host }}
  issuerRef:
    name: internal-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io