apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.app.name }}:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: greeter_server
    git:
      uri: https://github.com/trevorbox/service-mesh-grpc.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: IMPORT_URL
        value: github.com/trevorbox/service-mesh-grpc/blob/master/greeter_server
      - name: INSTALL_URL
        value: github.com/trevorbox/service-mesh-grpc/blob/master/greeter_server
      from:
        kind: ImageStreamTag
        name: golang:1.11.5
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 1
  triggers:
  - type: ImageChange
