apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: example
    app.kubernetes.io/component: greeter-server
    app.kubernetes.io/instance: greeter-server
    version: v1
  name: greeter-server
  namespace: go
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: greeter-server
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configMap":{"name":"proto-descriptor","items":[{"key":"proto.pb","path":"proto.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
      creationTimestamp: null
      labels:
        app: example
        deploymentconfig: greeter-server
        version: v1
    spec:
      containers:
      - env:
        - name: IMPORT_URL
          value: github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_server
        image: image-registry.openshift-image-registry.svc:5000/go/greeter-server@sha256:c4d843b5c190d25d63eb76df37387f1e7b7077b3ca928bc195f144e25b895cdc
        imagePullPolicy: Always
        name: greeter-server
        ports:
        - containerPort: 50051
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: example
      serviceAccountName: example
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - greeter-server
      from:
        kind: ImageStreamTag
        name: greeter-server:latest
        namespace: go
    type: ImageChange
