apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
    service: example
  name: example
  namespace: go
spec:
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 50051
  - name: http1
    port: 8081
    protocol: TCP
    targetPort: 50051
  selector:
    app: example
  sessionAffinity: None
  type: ClusterIP
