apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
    service: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 50051
  - name: http1
    port: 8081
    protocol: TCP
    targetPort: 50051
  selector:
    app: {{ .Values.app.name }}
  sessionAffinity: None
  type: ClusterIP
