apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example
  namespace: go
spec:
  host: example
  subsets:
  - labels:
      version: v1
    name: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL