---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
  namespace: go
spec:
  gateways:
  - istio-system/api
  hosts:
  - api-istio-system.apps.cluster-c718.c718.sandbox761.opentlc.com
  http:
  # Routes for json paths
  - match:
    - uri:
        prefix: /v1/greeter
    route:
    - destination:
        host: example
        port:
          number: 8081
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - OPTIONS
      - GET
      - POST
      - DELETE
      - PATCH
      allowCredentials: true
      allowHeaders:
      - Content-Type
      - Authorization
      maxAge: "1h"
  - match:
    - uri:
        prefix: /helloworld.Greeter
    route:
    - destination:
        host: example
        subset: v1
        port:
          number: 8080

...