---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  gateways:
  - {{ .Values.control_plane.namespace }}/api
  hosts:
  - {{ .Values.control_plane.ingressgateway.host }}
  http:
  # Routes for json paths
  - match:
    - uri:
        prefix: /v1/greeter
    route:
    - destination:
        host: {{ .Values.app.name }}
        port:
          number: 8081
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - OPTIONS
      - GET
      - POST
      - DELETE
      - PATCH
      allowCredentials: true
      allowHeaders:
      - Content-Type
      - Authorization
      maxAge: "1h"
  - match:
    - uri:
        prefix: /helloworld.Greeter
    route:
    - destination:
        host: {{ .Values.app.name }}
        subset: v1
        port:
          number: 8080

...