---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-v1
  namespace: {{ .Values.app.namespace }} 
  labels:
    app: {{ .Values.app.name }}
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configMap":{"name":"helloworld-proto-descriptor","items":[{"key":"proto.pb","path":"proto.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
      labels:
        app: {{ .Values.app.name }}
        version: v1
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: image-registry.openshift-image-registry.svc:5000/{{ .Values.app.namespace }}/{{ .Values.app.name }}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          protocol: TCP
        env:
          - name: IMPORT_URL
            value: github.com/trevorbox/service-mesh-grpc/blob/master/greeter-server/helloworld
...
